"""Node provisioning endpoints — v4.2.

GET /api/provision/ca serves the Pi's local certificate authority (PEM)
for the firmware's trust-on-first-use pinning: a node with "Secure MQTT"
enabled fetches this once over plain HTTP at provision time, stores the
PEM in NVS, and connects to the broker's TLS listener (8883) with the
pinned CA from then on. TOFU has SSH semantics — the first fetch trusts
the LAN; every later connection authenticates the broker.

The CA is generated by install.sh (or the dev-only setup.sh) into
<repo>/config/mosquitto/certs/ca.crt. Under Docker the server container sees
only that one public file, bind-mounted read-only at /certs/ca.crt (see
docker-compose.yml — never the certs directory, which holds the private
keys). On bare metal the repo path is resolved from this file, not the CWD,
because the documented dev run is `cd server && uvicorn …`.

This endpoint 404s until the CA exists. A node whose CA fetch fails logs a
Serial warning and connects over plaintext 1883, so a 404 here silently
disables TLS for every "Secure MQTT" node — keep the paths above in sync
with the compose mount (tests/test_provision_ca.py pins both).
"""

from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse

router = APIRouter()

_REPO_ROOT = Path(__file__).resolve().parents[2]

_CA_PATHS = (
    Path("/certs/ca.crt"),                                   # container mount
    _REPO_ROOT / "config" / "mosquitto" / "certs" / "ca.crt",  # bare-metal checkout
)


@router.get("/ca", response_class=PlainTextResponse)
async def get_ca() -> str:
    for p in _CA_PATHS:
        if p.is_file():
            pem = p.read_text()
            # Serve only the certificate — refuse to ever ship a file that
            # somehow contains key material.
            if "PRIVATE KEY" in pem:
                raise HTTPException(500, "CA file is misconfigured")
            return pem
    raise HTTPException(
        404, "No broker CA found — run ./install.sh on the Pi to generate it "
             "(Docker: it is mounted at /certs/ca.crt)")
