"""Node provisioning endpoints — v4.2.

GET /api/provision/ca serves the Pi's local certificate authority (PEM)
for the firmware's trust-on-first-use pinning: a node with "Secure MQTT"
enabled fetches this once over plain HTTP at provision time, stores the
PEM in NVS, and connects to the broker's TLS listener (8883) with the
pinned CA from then on. TOFU has SSH semantics — the first fetch trusts
the LAN; every later connection authenticates the broker.

The CA is generated by setup.sh into config/mosquitto/certs/ca.crt; this
endpoint 404s until that has run (plaintext 1883 keeps working either
way — TLS is opt-in per node).
"""

from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse

router = APIRouter()

_CA_PATHS = (
    Path("/certs/ca.crt"),                       # container mount
    Path("config/mosquitto/certs/ca.crt"),       # bare-metal checkout
)


@router.get("/ca", response_class=PlainTextResponse)
async def get_ca() -> str:
    for p in _CA_PATHS:
        if p.is_file():
            pem = p.read_text()
            # Serve only the certificate — refuse to ever ship a file that
            # somehow contains key material.
            if "PRIVATE KEY" in pem:
                raise HTTPException(500, "CA file is misconfigured")
            return pem
    raise HTTPException(
        404, "No broker CA generated — run setup.sh to enable TLS MQTT")
