"""Validate docker-compose.yml — catches image typos, missing services, wrong env vars."""

import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
COMPOSE_PATH = REPO_ROOT / "docker-compose.yml"

# Scripts that run throwaway eclipse-mosquitto containers (mosquitto_passwd
# for the broker's password file). They must use the exact image the broker
# runs, or a hash/format change between versions can lock the Pi out.
# install.sh carries its own copy (curl|bash path); everything else sources
# scripts/lib/broker.sh.
BROKER_IMAGE_OWNERS = (
    REPO_ROOT / "install.sh",
    REPO_ROOT / "scripts" / "lib" / "broker.sh",
)
BROKER_LIB_USERS = (
    REPO_ROOT / "setup.sh",
    REPO_ROOT / "scripts" / "add-node-mqtt-user.sh",
    REPO_ROOT / "scripts" / "rotate-mqtt-creds.sh",
)


def _load_compose() -> dict:
    return yaml.safe_load(COMPOSE_PATH.read_text())


def _bind_mounts(service: dict) -> dict[str, dict]:
    """target → long-syntax bind mount."""
    return {
        v["target"]: v
        for v in service.get("volumes", [])
        if isinstance(v, dict) and v.get("type") == "bind"
    }


def _server_env() -> dict[str, str]:
    env = _load_compose()["services"]["server"]["environment"]
    return dict(e.split("=", 1) for e in env)


def test_compose_has_all_services():
    services = _load_compose()["services"]
    for name in ("server", "mqtt", "ntfy", "ui"):
        assert name in services, f"Missing service: {name}"


def test_ntfy_image_is_correct():
    services = _load_compose()["services"]
    assert services["ntfy"]["image"] == "binwiederhier/ntfy:v2.28.0"


def test_mosquitto_image_is_correct():
    services = _load_compose()["services"]
    assert services["mqtt"]["image"] == "eclipse-mosquitto:2.1.2-alpine"


def test_every_image_is_pinned_to_an_exact_version():
    """install.sh runs `compose pull` on every update: a floating tag
    (`eclipse-mosquitto:2` silently moved 2.0.x → 2.1.x, with option
    deprecations) changes the broker without any code change or test."""
    for name, svc in _load_compose()["services"].items():
        image = svc.get("image")
        if image is None:
            continue  # built locally
        assert ":" in image, f"{name}: image {image!r} has no tag (implicit :latest)"
        tag = image.rsplit(":", 1)[1]
        assert re.match(r"^v?\d+\.\d+(\.\d+)?(-[a-z0-9.]+)?$", tag), (
            f"{name}: image tag {tag!r} is not an exact version"
        )


def test_scripts_use_the_same_broker_image_as_compose():
    image = _load_compose()["services"]["mqtt"]["image"]
    for script in BROKER_IMAGE_OWNERS:
        used = set(re.findall(r"eclipse-mosquitto:[\w.\-]+", script.read_text()))
        assert used == {image}, (
            f"{script.name} uses {sorted(used)} but the broker runs {image}"
        )
    for script in BROKER_LIB_USERS:
        body = script.read_text()
        assert "scripts/lib/broker.sh" in body, f"{script.name} no longer uses the shared broker helpers"
    # …and no other shell script pins a different broker image.
    for script in [*REPO_ROOT.glob("*.sh"), *(REPO_ROOT / "scripts").rglob("*.sh")]:
        used = set(re.findall(r"eclipse-mosquitto:[\w.\-]+", script.read_text()))
        assert used <= {image}, f"{script.name} uses {sorted(used)}; the broker runs {image}"


def test_server_env_vars_use_correct_prefix():
    services = _load_compose()["services"]
    env_list = services["server"]["environment"]
    for env in env_list:
        key = env.split("=")[0]
        assert key.startswith("SPOREPRINT_"), f"Env var {key} doesn't use SPOREPRINT_ prefix"


def test_server_receives_the_command_signing_and_ota_keys():
    """server/.dockerignore excludes .env and there is no env_file:, so a
    setting reaches the container ONLY if it is listed here. Without these,
    scripts/provision-node.sh's key never reached the server: keyed nodes
    rejected every (unsigned) command, and a cloud-configured Pi in 'auto'
    mode refused every command with no way to supply the key."""
    env = _server_env()
    assert env.get("SPOREPRINT_MQTT_HMAC_KEY") == "${SPOREPRINT_MQTT_HMAC_KEY:-}"
    # An EMPTY value fails the Literal["auto","always","never"] check and the
    # server crash-loops at boot — the default must be spelled out.
    assert env.get("SPOREPRINT_MQTT_REQUIRE_SIGNING") == "${SPOREPRINT_MQTT_REQUIRE_SIGNING:-auto}"
    assert env.get("SPOREPRINT_OTA_PUBKEY_B64") == "${SPOREPRINT_OTA_PUBKEY_B64:-}"
    # Name printed by scripts/generate-ota-keypair.py; cloud/ota.py falls back to it.
    assert env.get("SPOREPRINT_OTA_PUBKEY") == "${SPOREPRINT_OTA_PUBKEY:-}"


def test_generated_broker_files_are_never_auto_created_as_directories():
    """passwd, certs and ca.crt are generated by install.sh. With the short
    `./a:/b` syntax a missing source is silently created by Docker as a
    root-owned DIRECTORY — the broker then dies ('pwfile is a directory')
    and a later install.sh cannot even write the file. Long syntax with
    create_host_path: false makes a bare `docker compose up` fail loudly."""
    services = _load_compose()["services"]
    required = {
        "mqtt": ("/mosquitto/config/passwd", "/mosquitto/certs"),
        "server": ("/certs/ca.crt",),
    }
    for svc_name, targets in required.items():
        mounts = _bind_mounts(services[svc_name])
        for target in targets:
            assert target in mounts, f"{svc_name}: no long-syntax bind for {target}"
            mount = mounts[target]
            assert mount.get("read_only") is True, f"{svc_name}:{target} must be read-only"
            assert (mount.get("bind") or {}).get("create_host_path") is False, (
                f"{svc_name}:{target} would be auto-created as a directory"
            )


def test_every_service_rotates_its_logs():
    """The json-file driver is unbounded by default; the broker logs every
    connect/disconnect to stdout. Months of that fill the Pi's SD card and
    SQLite then fails with 'database or disk is full'."""
    for name, svc in _load_compose()["services"].items():
        logging_cfg = svc.get("logging") or {}
        opts = logging_cfg.get("options") or {}
        assert opts.get("max-size"), f"{name}: no log max-size"
        assert opts.get("max-file"), f"{name}: no log max-file"


def test_server_publishes_the_ota_push_callback_port():
    """espota: the node connects BACK over TCP to the port the Pi advertises.
    Behind the compose bridge network that port must be fixed and
    published, or every push ends 'node … never connected back'."""
    from app.hardware import ota_push

    port = ota_push.CALLBACK_PORT
    assert port and port != 8000
    ports = [str(p) for p in _load_compose()["services"]["server"]["ports"]]
    assert any(p.startswith(f"{port}:{port}") for p in ports), (
        f"server does not publish the OTA callback port {port}: {ports}"
    )


def test_ui_port_mapping():
    services = _load_compose()["services"]
    ports = services["ui"]["ports"]
    assert any("3001:80" in str(p) for p in ports), f"UI should map to port 3001, got {ports}"
