"""docs/wiring-tier*.svg are generated by scripts/wiring_svg/.

A hand edit to a tier SVG would be silently reverted the next time someone
regenerates the diagrams; a generator change that is not rebuilt leaves the
docs stale. Either way the committed SVG and its generator must agree.
"""
import importlib.util
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def test_tier_svgs_match_their_generators():
    spec = importlib.util.spec_from_file_location(
        "wiring_svg_build", REPO / "scripts" / "wiring_svg" / "build.py")
    build = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build)
    assert build.stale() == [], (
        "docs/wiring-tier*.svg differ from scripts/wiring_svg/ — edit the generators and run "
        "python3 scripts/wiring_svg/build.py"
    )
